"""Add like_count to Comment

Revision ID: 398171cf062b
Revises: 2c6a123a69d6
Create Date: 2025-12-26 17:38:20.705992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398171cf062b'
down_revision: Union[str, Sequence[str], None] = '2c6a123a69d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'like_count')
    # ### end Alembic commands ###
